name: Test

on:
  push:
    branches:
      - main

jobs:
  test-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd Client
          npm ci --legacy-peer-deps
      - name: Run tests
        run: |
          cd Client
          npm test

  test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd Server
          npm ci --legacy-peer-deps
      - name: Run tests
        run: |
          cd Server
          npm test
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t mentorshalabackend .
      - name: Push Docker image
        run: docker push mentorshalabackend
      - name: Render Deploy
        uses: renderapp/github-action@1.4.1
        with:
          render_account_id: ${{ secrets.RENDER_ACCOUNT_ID }}
          render_api_key: ${{ secrets.RENDER_API_KEY }}
          render_yaml_path: ./test.yaml

